version: "1.0.0"
x-compose-config:
  project_name: todoappgroup

services:
  app:
    container_name: app
    image: node:18-alpine
    depends_on: 
      - mysql
    command: sh -c "yarn install && yarn run dev"
    ports:
      - 8000:3000
      - 8001:3000
    working_dir: /app
    volumes:
      - ./:/app
    # volumes:
    #   - type: bind
    #     source: ./ 
    #     target: /app
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: todos
  mysql:
    container_name: mysql
    image: mysql:8.0
    ports:
      - 3309:3306
      - 3306:3306
    volumes:
      - todo-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: todos
volumes:
  todo-mysql-data:
    name: todo-mysql-data